#!/usr/bin/env bash
# rotate-supabase.sh — paste-safe Supabase token rotation
# Usage:  bash c:/aoe-unified-final-main/scripts/rotate-supabase.sh
#
# What it does:
#   1. Prompts for the new token with -s (silent, no echo, not stored in history)
#   2. Validates prefix (sbp_) and minimum length (40 chars)
#   3. Writes the full token ONLY to c:/aoe-unified-final/.env.supabase (chmod 600, gitignored)
#   4. Writes a prefix+length fingerprint to the prime-ops state file — never the full token
#   5. Prompts for the revocation timestamp and records it
#   6. Scrubs this invocation from shell history
#
# What it does NOT do:
#   - Never prints the full token
#   - Never writes the full token to a JSON settings file
#   - Never commits anything to git

set -euo pipefail

STATE_FILE="c:/aoe-unified-final-main/.claude/state/prime-ops.json"
ENV_FILE="c:/aoe-unified-final/.env.supabase"
GITIGNORE="c:/aoe-unified-final/.gitignore"

# --- 1. prompt (silent)
echo ""
echo "Paste the NEW Supabase token below. Input is hidden. Press Enter when done."
echo "  (Token will NOT appear on screen and will NOT be stored in shell history.)"
echo ""
read -r -s -p "new token> " NEW_TOKEN
echo ""

# --- 2. validate shape
if [[ -z "${NEW_TOKEN}" ]]; then
  echo "ERROR: no token received. Aborting."
  exit 1
fi
if [[ ! "${NEW_TOKEN}" =~ ^sbp_[A-Za-z0-9_]{36,}$ ]]; then
  echo "ERROR: token does not match expected shape (sbp_ + >=36 alphanumeric/_ chars)."
  echo "       length received: ${#NEW_TOKEN}"
  echo "       Aborting — no files written."
  unset NEW_TOKEN
  exit 1
fi

PREFIX="${NEW_TOKEN:0:12}"
LENGTH="${#NEW_TOKEN}"

# --- 3. prompt for revocation timestamp
echo ""
echo "Revocation timestamp (when you revoked the old sbp_7105c548 token)."
echo "Format: YYYY-MM-DD HH:MM UTC   (or press Enter to use current time)"
read -r -p "revoked at> " REVOKED_AT
if [[ -z "${REVOKED_AT}" ]]; then
  REVOKED_AT="$(date -u '+%Y-%m-%d %H:%M UTC')"
fi

NOW_ISO="$(date -u '+%Y-%m-%dT%H:%MZ')"

# --- 4. write env file (chmod 600) — this is the ONLY place the full token lives
mkdir -p "$(dirname "${ENV_FILE}")"
{
  echo "# Generated by rotate-supabase.sh at ${NOW_ISO}"
  echo "# DO NOT COMMIT. Gitignored by convention."
  echo "SUPABASE_TOKEN=${NEW_TOKEN}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}" 2>/dev/null || true

# --- 4b. ensure gitignore covers it
if [[ -f "${GITIGNORE}" ]]; then
  if ! grep -qxF ".env.supabase" "${GITIGNORE}"; then
    echo ".env.supabase" >> "${GITIGNORE}"
  fi
else
  echo ".env.supabase" > "${GITIGNORE}"
fi

# --- 5. update state file via node (jq may not be present on git-bash) — fingerprint only
PREFIX_ESC="${PREFIX}" LENGTH_ESC="${LENGTH}" REVOKED_ESC="${REVOKED_AT}" NOW_ESC="${NOW_ISO}" \
node -e "
const fs = require('fs');
const p = process.env;
const path = '${STATE_FILE}';
const s = JSON.parse(fs.readFileSync(path, 'utf8'));
s.last_run = p.NOW_ESC;
s.tasks.supabase_rotation.status = 'completed';
s.tasks.supabase_rotation.completed_at = p.NOW_ESC;
s.tasks.supabase_rotation.verification = {
  new_token_prefix: p.PREFIX_ESC,
  new_token_length: parseInt(p.LENGTH_ESC, 10),
  revoked_at: p.REVOKED_ESC,
  recorded_at: p.NOW_ESC,
  storage_location: '${ENV_FILE}',
  full_value_persisted: false
};
fs.writeFileSync(path, JSON.stringify(s, null, 2) + '\n');
console.log('state updated.');
"

# --- 6. scrub token from memory + shell history
unset NEW_TOKEN
history -d "$(history 1 | awk '{print $1}')" 2>/dev/null || true

# --- 7. fingerprint-only confirmation
cat <<EOF

ROTATION RECORDED (fingerprint only — full token not shown)
  prefix   : ${PREFIX}...
  length   : ${LENGTH}
  revoked  : ${REVOKED_AT}
  stored   : ${ENV_FILE}  (chmod 600, gitignored)
  state    : ${STATE_FILE}  (task=completed)

Next: any process that needs the token should read \$SUPABASE_TOKEN
      from ${ENV_FILE}, not from any settings JSON.
EOF
