#!/usr/bin/env bash
# Reads logs/discovery.csv, computes empirical thresholds, writes scripts/thresholds.env.
# Output is sourced by threshold_loop.sh and observability tooling.
#
# Rules (from calibration spec):
#   latency_threshold = avg + (2 * std)
#   memory_threshold  = avg * 1.5
#   failure_threshold = max_consecutive_failures + 1  (min 2)

set -u

CSV="${DISCOVERY_CSV:-logs/discovery.csv}"
OUT="${THRESHOLDS_ENV:-scripts/thresholds.env}"

[ -s "$CSV" ] || { echo "[derive] no data at $CSV"; exit 1; }
ROWS=$(($(wc -l < "$CSV") - 1))
[ "$ROWS" -ge 5 ] || { echo "[derive] too few rows ($ROWS) — run discovery longer"; exit 1; }

awk -F, -v OUT="$OUT" '
  NR == 1 { next }
  {
    code = $2 + 0
    lat  = $3 + 0
    mem  = $4 + 0
    n_lat++
    lat_sum += lat
    lat_arr[n_lat] = lat
    if (mem > 0) { n_mem++; mem_sum += mem }
    if (code != 200) { c++; if (c > max_c) max_c = c } else { c = 0 }
    if (code == 200) ok++
    total++
  }
  END {
    avg_lat = n_lat ? lat_sum / n_lat : 0
    for (i = 1; i <= n_lat; i++) var += (lat_arr[i] - avg_lat) ^ 2
    std_lat = n_lat ? sqrt(var / n_lat) : 0
    avg_mem = n_mem ? mem_sum / n_mem : 0
    lat_threshold = avg_lat + 2 * std_lat
    mem_threshold = avg_mem * 1.5
    fail_threshold = max_c + 1
    if (fail_threshold < 2) fail_threshold = 2
    ok_rate = total ? (ok / total) * 100 : 0

    printf "# generated by derive_thresholds.sh at %s UTC\n", strftime("%Y-%m-%dT%H:%M:%SZ", systime(), 1) > OUT
    printf "# rows=%d ok=%d ok_rate=%.2f%% max_consecutive_failures=%d\n", total, ok, ok_rate, max_c >> OUT
    printf "AVG_LATENCY_S=%.6f\n", avg_lat >> OUT
    printf "STD_LATENCY_S=%.6f\n", std_lat >> OUT
    printf "LATENCY_THRESHOLD_S=%.6f\n", lat_threshold >> OUT
    printf "AVG_MEMORY_MB=%.2f\n", avg_mem >> OUT
    printf "MEMORY_THRESHOLD_MB=%.2f\n", mem_threshold >> OUT
    printf "FAIL_THRESHOLD=%d\n", fail_threshold >> OUT
    close(OUT)

    printf "[derive] rows=%d ok_rate=%.2f%%\n", total, ok_rate
    printf "[derive] latency: avg=%.4fs std=%.4fs  threshold=%.4fs\n", avg_lat, std_lat, lat_threshold
    printf "[derive] memory : avg=%.2fMB                threshold=%.2fMB\n", avg_mem, mem_threshold
    printf "[derive] failures: max_consec=%d              N=%d\n", max_c, fail_threshold
    printf "[derive] wrote %s\n", OUT
  }
' "$CSV"
